# Generated by Django 6.0.4 on 2026-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('timeout', models.IntegerField()),
                ('alert_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=10)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
